color_palette:
  dark_bg_fore: "#D9D9D9"
  dark_bg_back: "#054062"
api:
  mapbox: pk.eyJ1IjoiZGN5Y2xlIiwiYSI6ImNrb2J3NGZzOTAxYnAycHFkbzkxbzlzZWYifQ.DdCrbOuTjU1z4Z-wi2NpNA
  mapbox_desc: Dcycle Account Token, you should use your own here instead as this
    will change
items:
  - title: Michel et Michel Vidéaste
    lang: en
    langs:
      - lang: fr
        path: /jekyll/fr/
    home: /jekyll/jekyll.html
    menu:
      - id: home
        label: Home
        href: /jekyll/jekyll.html
